### ISSUE TITLE
建立odoo系统

### ISSUE THREAD

**Issue by huming0618** [huming0618/ds-shop#6]
- 进销存流程
- API
- 系统备份

**Comment by huming0618** [comment]
## 产品信息
- [ ] 适应服装产品
- [ ] 条形码

**Comment by huming0618** [comment]
## 销售
- [ ] 销售点管理
- [ ] 销售流程

**Comment by huming0618** [comment]
## 库存
- [ ] 报表

**Comment by huming0618** [comment]
## 定价
- [ ] 定价流程
- [ ] 关联销售

**Comment by huming0618** [comment]
## API
- [ ] 流程API
- [ ] 数据API
- [ ] 报表API

**Comment by huming0618** [comment]
## 页面问题 odoo.define is not a function
在使用基于odoo-docker建立的站点时， 前端报错导致页面异常

`caught TypeError: odoo.define is not a function`

参考 https://github.com/odoo/odoo/issues/13808 

1。在psql下执行 `DELETE FROM ir_attachment WHERE url LIKE '/web/content/%';` 
2。重启docker-odoo镜像

问题解决

**Comment by huming0618** [comment]
根据[odoo-docker](https://hub.docker.com/_/odoo/)docker-compose.yml配置volumes
```
version: '2'
services:
  web:
    image: odoo:10.0
    network_mode: "host"    
    ports:
      - "8069:8069"
    environment:
      - HOST=localhost
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
```
