### ISSUE TITLE
Odoo - 产品信息

### ISSUE THREAD

**Issue by huming0618** [huming0618/ds-shop#9]
- 产品分类
- 产品信息项

**Comment by huming0618** [comment]
Reference 
- [Add the customized field](https://www.odoo.com/forum/help-1/question/add-custom-fields-to-sales-order-45074)
- [Odoo开发之扩展现有模块](http://blog.csdn.net/sunansheng/article/details/50807776)

**Comment by huming0618** [comment]
根据[odoo-docker](https://hub.docker.com/_/odoo/)docker-compose.yml配置volumes
```
version: '2'
services:
  web:
    image: odoo:10.0
    network_mode: "host"    
    ports:
      - "8069:8069"
    environment:
      - HOST=localhost
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
```
